version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./prometheus.yaml:/etc/prometheus.yaml
    command:
      - "--config.file=/etc/prometheus.yaml"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    network_mode: "host"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana.yaml:/etc/grafana/provisioning/datasources/datasource.yaml

volumes:
  grafana-data:

